master:
  max_pool_size: 6
  max_exp_count: 50.0
  lead_size: 5
  pop_size: 2
  overfitting:
    threshold: 0.01 # if current*overfitting_threshold > next: overfitting is happening
    min_grow: 10000 # check overfitting only if experiment count is more than this number
    min_transfer: 1000 # finalize ga switch after this number of evaluations have been collected

worker:
  mrate: 0.01
  samples: 30
  tset_slice: 100
  vset_slice: 600
  lead_size: 10
